#!/usr/bin/env python

from client import Client
from lists  import get_or_create_list as get_list
from pprint import pprint
from cards  import * 
from files  import load_config, load_tasks_now

cl = Client()
my_bid = load_config()['board_id']

def list_minus_list(list_a, list_b):
  c = []
  for a in list_a:
    exists = False

    for b in list_b:
      if a['name'] == b['name']:
        exists = True
        break

    if not exists:
      c.append(a)

  return c


task_lists = load_tasks_now()
pprint(task_lists)
    
for name, tasks in task_lists.items():
  print("")
  print(name)
  lid = get_list(my_bid, name)
  cards = get_cards(lid)
  pprint(list(map(lambda x: {'name': x['name']}, cards)))

  new_tasks = list_minus_list(tasks, cards)
  old_cards = list_minus_list(cards, tasks)
  current_cards = list_minus_list(cards, old_cards)

  for task in new_tasks:
    create_card(lid, task['name'], 'null')
    print("new task " + task['name'])

  for card in old_cards:
    close_card(card['id'])
    print("old cards " + card['name'])

  for card in current_cards:
    print("current card " + card['name'])
    if card['closed']:
      open_card(card['id'])


print("check cards")
for card in get_cards(get_list(my_bid, "Morning")):
  print("# " + card['name'] + " :: " + card['id'])
